#MODEL

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('/content/Train_data_classification.csv')
df

      intercolumnar distance   upper margin  ...  modular ratio  class
0                    0.117948     -0.220579  ...       0.541155      A
1                    0.809204     -0.094960  ...       0.244286      I
2                    0.080916      0.014957  ...      -0.028184      A
3                   -3.461768     -0.204876  ...      -5.460407      F
4                    0.056229     -0.730905  ...       1.319049      A
...                       ...           ...  ...            ...    ...
8339                -0.277055     -0.251983  ...       0.952766      X
8340                 0.019197     -0.173471  ...      -0.677208      F
8341                -0.128929      0.572391  ...      -0.298954      G
8342                 1.377020     -0.063555  ...      -0.349743      A
8343                -0.573307      0.376111  ...      -0.411272      G

[8344 rows x 11 columns]

In [3]:
df.info(
)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8344 entries, 0 to 8343
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   intercolumnar distance   8344 non-null   float64
 1   upper margin             8344 non-null   float64
 2   lower margin             8344 non-null   float64
 3   exploitation             8344 non-null   float64
 4   row number               8344 non-null   float64
 5   modular ratio            8344 non-null   float64
 6   interlinear spacing      8344 non-null   float64
 7   weight                   8344 non-null   float64
 8   peak number              8344 non-null   float64
 9   modular ratio            8344 non-null   float64
 10  class                    8344 non-null   object
dtypes: float64(10), object(1)
memory usage: 717.2+ KB

In [4]:
df.describe(
)

       intercolumnar distance   upper margin  ...  peak number   modular ratio
count              8344.000000   8344.000000  ...   8344.000000    8344.000000
mean                 -0.012469      0.043895  ...      0.016761       0.002508
std                   0.982288      4.360693  ...      1.107091       1.002965
min                  -3.498799     -2.426761  ...     -5.486218      -6.719324
25%                  -0.128929     -0.267686  ...     -0.372457      -0.510100
50%                   0.043885     -0.055704  ...      0.064084      -0.032662
75%                   0.204355      0.203385  ...      0.500624       0.523609
max                  11.819916    386.000000  ...     44.000000       4.671232

[8 rows x 10 columns]

In [5]:
df.corr()

                         intercolumnar distance   ...  modular ratio
intercolumnar distance                  1.000000  ...       0.004283
upper margin                           -0.036326  ...      -0.025252
lower margin                            0.033813  ...      -0.041496
exploitation                           -0.063020  ...       0.315185
row number                              0.491580  ...       0.151935
modular ratio                          -0.034524  ...       0.730268
interlinear spacing                     0.003870  ...       0.255065
weight                                 -0.062324  ...      -0.030581
peak number                             0.076065  ...       0.169297
modular ratio                           0.004283  ...       1.000000

[10 rows x 10 columns]

In [8]:
df.columns

Index(['intercolumnar distance ', 'upper margin', 'lower margin',
       'exploitation', 'row number', 'modular ratio ', 'interlinear spacing ',
       'weight ', 'peak number ', 'modular ratio', 'class'],
      dtype='object')

In [9]:
df['class'].head(10)

0    A
1    I
2    A
3    F
4    A
5    X
6    G
7    E
8    F
9    E
Name: class, dtype: object

In [10]:
cols=list(set(df.columns)-set(df.describe().columns))

In [11]:
from sklearn.preprocessing import LabelEncoder

In [12]:
for eachcol in cols:
  le=LabelEncoder()
  df[eachcol]=le.fit_transform(df[eachcol])

In [13]:
df

      intercolumnar distance   upper margin  ...  modular ratio  class
0                    0.117948     -0.220579  ...       0.541155      0
1                    0.809204     -0.094960  ...       0.244286      8
2                    0.080916      0.014957  ...      -0.028184      0
3                   -3.461768     -0.204876  ...      -5.460407      5
4                    0.056229     -0.730905  ...       1.319049      0
...                       ...           ...  ...            ...    ...
8339                -0.277055     -0.251983  ...       0.952766     10
8340                 0.019197     -0.173471  ...      -0.677208      5
8341                -0.128929      0.572391  ...      -0.298954      6
8342                 1.377020     -0.063555  ...      -0.349743      0
8343                -0.573307      0.376111  ...      -0.411272      6

[8344 rows x 11 columns]

In [14]:
df['class'].head(10)

0     0
1     8
2     0
3     5
4     0
5    10
6     6
7     4
8     5
9     4
Name: class, dtype: int64

In [15]:
x=df[['intercolumnar distance ', 'upper margin', 'lower margin',
       'exploitation', 'row number', 'modular ratio ', 'interlinear spacing ',
       'weight ', 'peak number ', 'modular ratio']].values

In [16]:
y=df['class'].values

In [17]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,train_size=0.8)

In [18]:
from sklearn.neighbors import KNeighborsClassifier

In [19]:
knn = KNeighborsClassifier(n_neighbors=5)

In [20]:
knn.fit(xtrain,ytrain.ravel())

KNeighborsClassifier()

In [21]:
ypred=knn.predict(xtest)

In [22]:
from sklearn.metrics import accuracy_score
accuracy_score(ytest,ypred)

0.7028160575194727

#prediction

In [23]:
df_test = pd.read_csv('/content/Test_data_classification.csv')

In [26]:
df_test

      intercolumnar distance   upper margin  ...  modular ratio  class
0                    0.130292     -0.314793  ...       0.400605    NaN
1                   -0.104241     -0.314793  ...      -1.312598    NaN
2                    0.019197     -0.040001  ...      -0.209421    NaN
3                   -0.326430     -0.652394  ...      -3.113659    NaN
4                    0.031541     -0.346197  ...      -1.852354    NaN
...                       ...           ...  ...            ...    ...
2081                -3.498799      0.007106  ...      -0.689649    NaN
2082                -0.091897     -0.118513  ...       2.580920    NaN
2083                -0.091897      0.258344  ...       0.004015    NaN
2084                 0.327793      0.501730  ...      -0.740413    NaN
2085                -0.314087      0.360409  ...      -0.134884    NaN

[2086 rows x 11 columns]

In [27]:
test =df_test[['intercolumnar distance ', 'upper margin', 'lower margin',
       'exploitation', 'row number', 'modular ratio ', 'interlinear spacing ',
       'weight ', 'peak number ', 'modular ratio']].values

In [39]:
ypred_test=knn.predict(test)

In [40]:
ypred_test

array([0, 2, 0, ..., 0, 6, 5])

In [41]:
ypred_test

array([0, 2, 0, ..., 0, 6, 5])

In [42]:
len(ypred_test)

2086

In [43]:
df_test['class'] = ypred_test

In [44]:
df_test

      intercolumnar distance   upper margin  ...  modular ratio  class
0                    0.130292     -0.314793  ...       0.400605      0
1                   -0.104241     -0.314793  ...      -1.312598      2
2                    0.019197     -0.040001  ...      -0.209421      0
3                   -0.326430     -0.652394  ...      -3.113659      0
4                    0.031541     -0.346197  ...      -1.852354      0
...                       ...           ...  ...            ...    ...
2081                -3.498799      0.007106  ...      -0.689649      4
2082                -0.091897     -0.118513  ...       2.580920      0
2083                -0.091897      0.258344  ...       0.004015      0
2084                 0.327793      0.501730  ...      -0.740413      6
2085                -0.314087      0.360409  ...      -0.134884      5

[2086 rows x 11 columns]

In [45]:
df_test.to_csv('ML035_classification.csv')